### PR TITLE
created new post modal on home screen

### PR DESCRIPTION
**Pull request by rishabhpandey7**
Looks something like this (buttons on modal don't really do nothing yet):
cerate

Also, I changed the button color from wireframe to a green gradient to match our theme.

┆Issue is synchronized with this [Trello card](https://trello.com/c/bdrylfHk) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by rishabhpandey7** [comment]
Nevermind, I will first merge timothy's PR since he already has a feed page setup and then I will link this modal to the button present there.

**Comment by rishabhpandey7** [comment]
So please don't pull this yet.

**Comment by goldenwo** [comment]
The post modal looks perfectly fine. The only problem I had was I needed to do `npm install masterial-ui-search-bar`.

**Review by goldenwo — APPROVED** [review]
The post modal looks perfectly fine. The only problem I had was I needed to do npm install masterial-ui-search-bar.

**Review by goldenwo — DISMISSED** [review]
Added the profile page to this branch

**Review by Borghese-Gladiator — APPROVED** [review]
- only need to remove material-ui-search-bar later (should use @material-ui/core to build one instead with styling instead because we're going to need to hold data as well)

**Pull request merged**
