### PR TITLE
added rockstar component

### PR DESCRIPTION
**Pull request by rishabhpandey7**
bgasd

### CODE REVIEW

**Comment by Borghese-Gladiator** [comment]
Hey @rishabhpandey7 
I'm thinking of a couple changes, but feel free to tell me which ones you think don't need to be done.
- changing snippets of what people said into a list. Maybe show 2 or 3 quotes over 1 paragraph.
- change header to say "Real Quotes" or just "Quotes"
- change the `require("react-chartjs").Pie` to an import (allows you to just import <PieChart /> rather than the whole library) - [more info here](https://stackoverflow.com/questions/46677752/the-difference-between-requirex-and-import-x)
- use actual spaces like `{" "}` instead of the `&nbsp;`
- change into 3 Grids with responsive breakpoints (John Doe+3 values, Pie Chart, and Snippets of what People Said) - so you can resize and they appear vertical instead of the fixed John Doe + 3 Values + Pie Chart => prob xs={12} sm={4}

**Comment by rishabhpandey7** [comment]
> Hey @rishabhpandey7
> 
> CHANGES Needed
> 
> * change profile photo to be responsive (just change px to theme.spacing(3) or whatever number)
> 
> CHANGES Recommended
> 
> * changing snippets of what people said into a list. Maybe show 2 or 3 quotes over 1 paragraph.
> * change header to say "Real Quotes" or just "Quotes"
> * change the `require("react-chartjs").Pie` to an import (allows you to just import  rather than the whole library) - [more info here](https://stackoverflow.com/questions/46677752/the-difference-between-requirex-and-import-x)
> * change into 3 Grids with responsive breakpoints (John Doe+3 values, Pie Chart, and Snippets of what People Said) - so you can resize and they appear vertical instead of the fixed John Doe + 3 Values + Pie Chart => prob xs={12} sm={4}
> 
> Let me know if you think these changes aren't that important. I'm okay with merging it as it is, but these could be improvements.

Changed the responsiveness, the chart library isn't being able to import without require, this could be an issue : https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam , so I left it as is.

**Comment by Borghese-Gladiator** [comment]
Hey, could you rebase this? I'm pretty sure master has changed

**Review by Borghese-Gladiator — APPROVED** [review]
@rishabhpandey7 
note that none of our pages wrap on smaller screen sizes.

also, you probably need a constants file with the color configurations (rather than duplicating it within the code - aqua, yellowgreen, pink)

next step is to make it dynamic rather than displaying hard coded values

also, you could make the style marginLeft be done with a Box element (ml={1}) and then it wouldn't be hard coded values

**Pull request merged**
